In [59]:
import pandas as pd

In [60]:
df = pd.read_csv("Customer-Churn-Records.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [61]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x = df.drop(columns=['Exited'])
y = df['Exited']
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [64]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
trf1 = ColumnTransformer([
    ('onehot',OneHotEncoder(drop='first', sparse_output=False , handle_unknown= 'ignore'),['Geography','Gender','Card Type'])
],remainder='passthrough')

In [65]:
trf1.set_output(transform='pandas')
x_train = trf1.fit_transform(x_train)
x_test = trf1.transform(x_test)

In [66]:
x_train

,onehot__Geography_Germany,onehot__Geography_Spain,onehot__Gender_Male,onehot__Card Type_GOLD,onehot__Card Type_PLATINUM,onehot__Card Type_SILVER,remainder__CreditScore,remainder__Age,remainder__Tenure,remainder__Balance,remainder__NumOfProducts,remainder__HasCrCard,remainder__IsActiveMember,remainder__EstimatedSalary,remainder__Complain,remainder__Satisfaction Score,remainder__Point Earned
9254,0.0,0.0,1.0,0.0,0.0,0.0,686,32,6,0.00,2,1,1,179093.26,0,2,510
1561,1.0,0.0,1.0,0.0,1.0,0.0,632,42,4,119624.60,2,1,1,195978.86,0,4,959
1670,0.0,1.0,1.0,0.0,0.0,1.0,559,24,3,114739.92,1,1,0,85891.02,1,4,327
6087,0.0,0.0,0.0,0.0,0.0,1.0,561,27,9,135637.00,1,1,0,153080.40,1,2,567
6669,0.0,0.0,1.0,0.0,1.0,0.0,517,56,9,142147.32,1,0,0,39488.04,1,3,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,0.0,0.0,1.0,0.0,0.0,1.0,768,54,8,69712.74,1,1,1,69381.05,0,3,569
5191,0.0,0.0,0.0,0.0,1.0,0.0,682,58,1,0.00,1,1,1,706.50,0,4,709
5390,0.0,0.0,0.0,0.0,0.0,1.0,735,38,1,0.00,3,0,0,92220.12,1,5,678
860,0.0,0.0,1.0,0.0,0.0,0.0,667,43,8,190227.46,1,1,0,97508.04,1,3,680
7270,1.0,0.0,1.0,0.0,0.0,0.0,697,51,1,147910.30,1,1,1,53581.14,0,4,639

In [67]:
from sklearn.preprocessing import StandardScaler

In [68]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [69]:
x_train = pd.DataFrame(x_train, columns=trf1.get_feature_names_out())
x_test = pd.DataFrame(x_test, columns=trf1.get_feature_names_out())

In [70]:
x_train

,onehot__Geography_Germany,onehot__Geography_Spain,onehot__Gender_Male,onehot__Card Type_GOLD,onehot__Card Type_PLATINUM,onehot__Card Type_SILVER,remainder__CreditScore,remainder__Age,remainder__Tenure,remainder__Balance,remainder__NumOfProducts,remainder__HasCrCard,remainder__IsActiveMember,remainder__EstimatedSalary,remainder__Complain,remainder__Satisfaction Score,remainder__Point Earned
0,-0.579467,-0.576388,0.913248,-0.577158,-0.580237,-0.573886,0.356500,-0.655786,0.345680,-1.218471,0.808436,0.649203,0.974817,1.367670,-0.509942,-0.720010,-0.430193
1,1.725723,-0.576388,0.913248,-0.577158,1.723434,-0.573886,-0.203898,0.294938,-0.348369,0.696838,0.808436,0.649203,0.974817,1.661254,-0.509942,0.704342,1.565908
2,-0.579467,1.734942,0.913248,-0.577158,-0.580237,1.742506,-0.961472,-1.416365,-0.695393,0.618629,-0.916688,0.649203,-1.025834,-0.252807,1.961007,0.704342,-1.243749
3,-0.579467,-0.576388,-1.094993,-0.577158,-0.580237,1.742506,-0.940717,-1.131148,1.386753,0.953212,-0.916688,0.649203,-1.025834,0.915393,1.961007,-0.720010,-0.176791
4,-0.579467,-0.576388,0.913248,-0.577158,1.723434,-0.573886,-1.397337,1.625953,1.386753,1.057449,-0.916688,-1.540351,-1.025834,-1.059600,1.961007,-0.007834,0.534515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,-0.579467,-0.576388,0.913248,-0.577158,-0.580237,1.742506,1.207474,1.435808,1.039728,-0.102301,-0.916688,0.649203,0.974817,-0.539860,-0.509942,-0.007834,-0.167899
7996,-0.579467,-0.576388,-1.094993,-0.577158,1.723434,-0.573886,0.314989,1.816097,-1.389442,-1.218471,-0.916688,0.649203,0.974817,-1.733882,-0.509942,0.704342,0.454493
7997,-0.579467,-0.576388,-1.094993,-0.577158,-0.580237,1.742506,0.865009,-0.085351,-1.389442,-1.218471,2.533560,-1.540351,-1.025834,-0.142765,1.961007,1.416518,0.316678
7998,-0.579467,-0.576388,0.913248,-0.577158,-0.580237,-0.573886,0.159323,0.390011,1.039728,1.827259,-0.916688,0.649203,-1.025834,-0.050826,1.961007,-0.007834,0.325569
7999,1.725723,-0.576388,0.913248,-0.577158,-0.580237,-0.573886,0.470655,1.150590,-1.389442,1.149720,-0.916688,0.649203,0.974817,-0.814568,-0.509942,0.704342,0.143297

In [71]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_train,y_train = smote.fit_resample(x_train,y_train)
x_test , y_test = smote.fit_resample(x_test , y_test)

In [72]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [73]:
x_train.shape

(12710, 17)

In [74]:
model = Sequential()
model.add(Dense(5, activation = 'sigmoid', input_dim = 17))
model.add(Dense(5, activation = 'sigmoid'))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [75]:
model.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [76]:
model.fit(x_train, y_train,epochs =  10, validation_split= 0.2)

Epoch 1/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6250 - loss: 0.6467 - val_accuracy: 0.0000e+00 - val_loss: 0.9047
Epoch 2/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7435 - loss: 0.4865 - val_accuracy: 0.9001 - val_loss: 0.5861
Epoch 3/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9890 - loss: 0.2455 - val_accuracy: 1.0000 - val_loss: 0.2896
Epoch 4/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9987 - loss: 0.1202 - val_accuracy: 1.0000 - val_loss: 0.1663
Epoch 5/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9987 - loss: 0.0715 - val_accuracy: 1.0000 - val_loss: 0.1075
Epoch 6/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9987 - loss: 0.0487 - val_accuracy: 1.0000 - val_loss: 0.0758
Epoch 7/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9988 - loss: 0.0361 - val_accuracy: 1.0000 - val_loss: 0.0565
Epoch 8/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9988 - loss: 0.0283 - val_accuracy: 1.0000 - val_loss: 0.0436
Epoch 9/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9988 - loss: 0.0231 - val_accuracy: 1.0000 - val_loss: 0.0346
Epoch 10/10
318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9988 - loss: 0.0195 - val_accuracy: 1.0000 - val_loss: 0.0279

In [77]:
y_pred = model.predict(x_test)

101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [78]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
y_pred = np.where(y_pred>0.5,1,0)

In [79]:
accuracy_score(y_test ,y_pred)

0.9993777224642191

In [80]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1607
           1       1.00      1.00      1.00      1607

    accuracy                           1.00      3214
   macro avg       1.00      1.00      1.00      3214
weighted avg       1.00      1.00      1.00      3214

In [81]:
import joblib

# Run this inside your notebook
#joblib.dump(scaler, "scaler.pkl")
#joblib.dump(model, "model.pkl")
# replace 'model' with your fitted estimator variable

In [82]:
joblib.dump(trf1, "transformer.pkl")

['transformer.pkl']